/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guru;

import app_interface.Koneksi;
import com.mysql.cj.jdbc.MysqlDataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class Setting extends javax.swing.JFrame implements Koneksi{
    Connection conn;
    ResultSet rs;
    PreparedStatement ps;
    MysqlDataSource dataSource;
    
    /**
     * Creates new form Setting
     */
    public Setting() {
        initComponents();
        connect(); 
    }
    
    @Override
    public final void connect() {
        dataSource = new MysqlDataSource();
        dataSource.setURL(Koneksi.DB_URL);
        dataSource.setUser(Koneksi.DB_USERNAME);
        dataSource.setPassword(Koneksi.DB_PASSWORD); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        logo1 = new javax.swing.JLabel();
        labelNamaApp1 = new javax.swing.JLabel();
        labelMottoApp1 = new javax.swing.JLabel();
        labelSetting = new javax.swing.JLabel();
        buttonKembali = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        tfNama = new javax.swing.JTextField();
        tfUmur = new javax.swing.JTextField();
        tfKontak = new javax.swing.JTextField();
        tfHarga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfSd = new javax.swing.JTextField();
        tfSmp = new javax.swing.JTextField();
        tfKuliah = new javax.swing.JTextField();
        tfSma = new javax.swing.JTextField();
        buttonUbah = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        tfPassword = new javax.swing.JTextField();
        cbJenisKelamin = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(45, 118, 232));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 160));

        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/navigation.png"))); // NOI18N

        labelNamaApp1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        labelNamaApp1.setForeground(new java.awt.Color(255, 255, 255));
        labelNamaApp1.setText("SIBIRU");

        labelMottoApp1.setForeground(new java.awt.Color(255, 255, 255));
        labelMottoApp1.setText("School Online");

        labelSetting.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelSetting.setForeground(new java.awt.Color(255, 255, 255));
        labelSetting.setText("Akun");

        buttonKembali.setText("Kembali");
        buttonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(buttonKembali)
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelNamaApp1)
                    .addComponent(labelMottoApp1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelSetting)
                .addGap(71, 71, 71))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(labelNamaApp1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelMottoApp1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonKembali)
                        .addGap(4, 4, 4)
                        .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 300));

        jLabel1.setText("ID");

        jLabel2.setText("Nama");

        jLabel3.setText("Umur");

        jLabel4.setText("Kontak");

        jLabel5.setText("Jenis Kelamin");

        jLabel6.setText("Harga Per Hari");

        tfId.setText(null);

        tfNama.setText(null);

        tfUmur.setText(null);

        tfKontak.setText(null);

        tfHarga.setText(null);

        jLabel7.setText("Riwayat Pendidikan");

        jLabel9.setText("SD");

        jLabel10.setText("SMP");

        jLabel11.setText("SMA");

        jLabel12.setText("Kuliah");

        tfSd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSdActionPerformed(evt);
            }
        });

        buttonUbah.setBackground(new java.awt.Color(0, 102, 102));
        buttonUbah.setForeground(new java.awt.Color(255, 255, 255));
        buttonUbah.setText("Simpan Perubahan");
        buttonUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUbahActionPerformed(evt);
            }
        });

        jButton2.setForeground(new java.awt.Color(255, 51, 51));
        jButton2.setText("Batalkan Perubahan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Email");

        jLabel13.setText("Password");

        tfEmail.setText(null);

        tfPassword.setText(null);

        cbJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pria", "Wanita" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonUbah))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfId)
                            .addComponent(tfNama)
                            .addComponent(tfUmur)
                            .addComponent(tfKontak)
                            .addComponent(tfHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(cbJenisKelamin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(31, 31, 31)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel9))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfSmp)
                                            .addComponent(tfSd)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfSma, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(48, 48, 48)
                                .addComponent(tfEmail))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(28, 28, 28)
                                .addComponent(tfPassword)))))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tfSd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tfSmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tfSma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(tfKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfUmur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfKontak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(cbJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonUbah)
                    .addComponent(jButton2))
                .addGap(62, 62, 62))
        );

        tfId.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfSdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSdActionPerformed

    private void buttonUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUbahActionPerformed
        // TODO add your handling code here:
        try {
            //========================= INFORMASI GURU =========================
            conn = dataSource.getConnection();
            
            String kueriInsert = "UPDATE guru_les SET nama = ?, umur = ?, kontak = ?, jenis_kelamin = ?, harga_per_hari = ?,"
                    + " email = ?, password = ? WHERE id_guru_les = ?";
            
            ps = conn.prepareStatement(kueriInsert);
            if (tfNama.getText().equals("") || tfUmur.getText().equals("") || tfKontak.getText().equals("") ||
                tfHarga.getText().equals("") || tfSd.getText().equals("") || tfSmp.getText().equals("") || 
                tfSma.getText().equals("") || tfKuliah.getText().equals("")) {
                    
                JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong!");
                return;
            }
                
            String jenis_kelamin = (String) cbJenisKelamin.getSelectedItem();
            int int_jenis_kelamin;
            if (jenis_kelamin.equals("Pria")) {
                int_jenis_kelamin = 0;
            }else {
                int_jenis_kelamin = 1;
            }
                
            ps.setString(1, tfNama.getText());
            ps.setString(2, (String) tfUmur.getText());
            ps.setString(3, tfKontak.getText());
            ps.setInt(4, int_jenis_kelamin);
            ps.setInt(5, Integer.parseInt(tfHarga.getText()));
            ps.setString(6, tfEmail.getText());
            ps.setString(7, tfPassword.getText());
            ps.setInt(8, Integer.parseInt(tfId.getText()));
                
            int rowAffected = ps.executeUpdate();
            
            //========================= RIWAYAT PENDIDIKAN =========================
            kueriInsert = "UPDATE riwayat_pendidikan SET sd = ?, smp = ?, sma = ?, kuliah = ? WHERE id_guru_les = ?";
            
            ps = conn.prepareStatement(kueriInsert);
            ps.setString(1, tfSd.getText());
            ps.setString(2, (String) tfSmp.getText());
            ps.setString(3, tfSma.getText());
            ps.setString(4, tfKuliah.getText());
            ps.setInt(5, Integer.parseInt(tfId.getText()));
            
            int rowAffected2 = ps.executeUpdate();
            
            if (rowAffected > 0 && rowAffected2 > 0) {
                JOptionPane.showMessageDialog(null, "Data Berhasil Diperbaharui!");   
            } else {
                JOptionPane.showMessageDialog(null, "Data Gagal Diperbaharui!");
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Eksepsi akses data: " + ex.getMessage());
        }
    }//GEN-LAST:event_buttonUbahActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            conn = dataSource.getConnection();
            
            //========================= INFORMASI GURU =========================
            String nama = null;
            String umur = null;
            String kontak = null;
            int jenis_kelamin = 0;
            String string_jenis_kelamin;
            String harga_per_hari = null;
            String email = null;
            String password = null;
        
            String kueriSelect = "SELECT * FROM guru_les WHERE id_guru_les = ?";
            ps = conn.prepareStatement(kueriSelect);
            ps.setInt(1, Integer.parseInt(tfId.getText()));
            rs = ps.executeQuery();
            
            while (rs.next()) {
                nama = rs.getString("nama");
                umur = rs.getString("umur");
                kontak = rs.getString("kontak");
                jenis_kelamin = rs.getInt("jenis_kelamin");
                harga_per_hari = String.valueOf(rs.getInt("harga_per_hari"));
                email = rs.getString("email");
                password = rs.getString("password");
            }
            
            if (jenis_kelamin == 0) {
                cbJenisKelamin.setSelectedItem("Pria");
            } else {
                cbJenisKelamin.setSelectedItem("Wanita");
            }
            
            tfNama.setText(nama);
            tfUmur.setText(umur);
            tfKontak.setText(kontak);
            tfHarga.setText(harga_per_hari);
            tfEmail.setText(email);
            tfPassword.setText(password);
            
            //========================= RIWAYAT PENDIDIKAN =========================
            String sd = null;
            String smp = null;
            String sma = null;
            String kuliah = null;
            
            kueriSelect = "SELECT * FROM riwayat_pendidikan WHERE id_guru_les = ?";
            ps = conn.prepareStatement(kueriSelect);
            ps.setInt(1, Integer.parseInt(tfId.getText()));
            rs = ps.executeQuery();
            
            while (rs.next()) {
                sd = rs.getString("sd");
                smp = rs.getString("smp");
                sma = rs.getString("sma");
                kuliah = rs.getString("kuliah");
            }
            
            tfSd.setText(sd);
            tfSmp.setText(smp);
            tfSma.setText(sma);
            tfKuliah.setText(kuliah);
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Eksepsi akses data: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buttonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliActionPerformed
        // TODO add your handling code here:
        guru.Home home = new Home();
        home.setId(Integer.parseInt(tfId.getText()));
        home.setNama(tfNama.getText());
        home.labelWelcome.setText("Halo, " + tfNama.getText()+ "!");
        
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>     

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Setting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonKembali;
    private javax.swing.JButton buttonUbah;
    protected javax.swing.JComboBox<String> cbJenisKelamin;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelMottoApp1;
    private javax.swing.JLabel labelNamaApp1;
    private javax.swing.JLabel labelSetting;
    private javax.swing.JLabel logo1;
    protected javax.swing.JTextField tfEmail;
    protected javax.swing.JTextField tfHarga;
    protected javax.swing.JTextField tfId;
    protected javax.swing.JTextField tfKontak;
    public javax.swing.JTextField tfKuliah;
    protected javax.swing.JTextField tfNama;
    protected javax.swing.JTextField tfPassword;
    public javax.swing.JTextField tfSd;
    public javax.swing.JTextField tfSma;
    public javax.swing.JTextField tfSmp;
    protected javax.swing.JTextField tfUmur;
    // End of variables declaration//GEN-END:variables
}
