/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package murid;

import app_interface.Koneksi;
import com.mysql.cj.jdbc.MysqlDataSource;
import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class CariLes extends javax.swing.JFrame implements Koneksi{
    Connection conn;
    ResultSet rs;
    PreparedStatement ps;
    MysqlDataSource dataSource;
    
    protected int id;
    
    /**
     * Creates new form CariLes
     */
    public CariLes() {
        initComponents();
        connect();
    }
    
    @Override
    public final void connect() {
        dataSource = new MysqlDataSource();
        dataSource.setURL(Koneksi.DB_URL);
        dataSource.setUser(Koneksi.DB_USERNAME);
        dataSource.setPassword(Koneksi.DB_PASSWORD); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        labelNamaApp = new javax.swing.JLabel();
        labelMottoApp = new javax.swing.JLabel();
        labelWelcome = new javax.swing.JLabel();
        buttonKembali = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbMatpel = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbDurasi = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        buttonCari = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tfHarga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbMulai = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbSelesai = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbMatpel2 = new javax.swing.JComboBox<>();
        cbJadwal = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbJadwal2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(45, 118, 232));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 160));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/navigation.png"))); // NOI18N

        labelNamaApp.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        labelNamaApp.setForeground(new java.awt.Color(255, 255, 255));
        labelNamaApp.setText("SIBIRU");

        labelMottoApp.setForeground(new java.awt.Color(255, 255, 255));
        labelMottoApp.setText("School Online");

        labelWelcome.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        labelWelcome.setForeground(new java.awt.Color(255, 255, 255));
        labelWelcome.setText("Cari Les");

        buttonKembali.setText("Kembali");
        buttonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelMottoApp))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(labelNamaApp)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelWelcome)
                .addGap(55, 55, 55))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonKembali)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(labelWelcome))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonKembali)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(labelNamaApp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelMottoApp)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Matpel");

        cbMatpel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matematika", "IPA", "Bahasa Inggris", "Biologi", "Fisika", "Kimia" }));

        jLabel3.setText("Durasi");

        cbDurasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Bulan (Mulai Rp 100.000,-)", "3 Bulan (Mulai Rp 300.000,-)", "4 Bulan (Mulai Rp 400.000,-)", "6 Bulan (Mulai Rp 600.000,-)", "12 Bulan (Mulai Rp 1.200.000,-)" }));
        cbDurasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDurasiActionPerformed(evt);
            }
        });

        jLabel8.setText("Jadwal Les");

        buttonCari.setBackground(new java.awt.Color(0, 102, 102));
        buttonCari.setForeground(new java.awt.Color(255, 255, 255));
        buttonCari.setText("Cari");
        buttonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariActionPerformed(evt);
            }
        });

        jLabel4.setText("Tawar Harga");

        jLabel5.setText("S.D");

        cbMulai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        cbMulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMulaiActionPerformed(evt);
            }
        });

        jLabel6.setText("Waktu");

        cbSelesai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        cbSelesai.setSelectedItem("Februari");

        jLabel7.setText("Matpel 2");

        cbMatpel2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Matematika", "IPA", "Bahasa Inggris", "Biologi", "Fisika", "Kimia" }));

        cbJadwal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu" }));

        jLabel9.setText("Jadwal Les 2");

        cbJadwal2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(224, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbMatpel2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(cbMulai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbMatpel, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(280, 280, 280))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbJadwal2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(24, 24, 24)
                                .addComponent(cbJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buttonCari))
                        .addGap(278, 278, 278))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMatpel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMatpel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbJadwal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonCari)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariActionPerformed
        // TODO add your handling code here:
        try {
            conn = dataSource.getConnection();
            
            if (tfHarga.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Mohon Lengkapi Data!");
                return;
            }
            
            String kueriInsert = "INSERT INTO transaksi (id_user, mata_pelajaran, mata_pelajaran_2, durasi_bulan, bulan_mulai,"
                    + " bulan_selesai, tawar_harga, jadwal, jadwal_2, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            
            int durasi = 0;
            switch (cbDurasi.getSelectedIndex()) {
                case 0 -> {
                    durasi = 1;
                }
                case 1 -> {
                    durasi = 3;
                }
                case 2 -> {
                    durasi = 4;
                }
                case 3 -> {
                    durasi = 6;
                }
                case 4 -> {
                    durasi = 12;
                }
            }
            
            String matpel2 = (String) cbMatpel2.getSelectedItem();
            if (matpel2.equals("-")) {
                matpel2 = null;
            }
            
            String jadwal2 = (String) cbJadwal2.getSelectedItem();
            if (jadwal2.equals("-")) {
                jadwal2 = null;
            }

            PreparedStatement ps = conn.prepareStatement(kueriInsert);
            ps.setInt(1, id);
            ps.setString(2, (String) cbMatpel.getSelectedItem());
            ps.setString(3, matpel2);
            ps.setInt(4, durasi);
            ps.setInt(5, cbMulai.getSelectedIndex() + 1);
            ps.setInt(6, cbSelesai.getSelectedIndex() + 1);
            ps.setInt(7, Integer.parseInt(tfHarga.getText()));
            ps.setString(8, (String) cbJadwal.getSelectedItem());
            ps.setString(9, jadwal2);
            ps.setString(10, "Mencari");
            
            int rowAffected = ps.executeUpdate();
            
            if (rowAffected > 0) {
               JOptionPane.showMessageDialog(null, "Terimakasih Telah Menggunakan Layanan Kami, Sekarang Tinggal Menunggu Tawaran Les Dari Pencarian Kakak"); 
            }
            
            //============================ DATA JFRAME KELAS ======================================
            Kelas kelas = new Kelas();
            String id_pesanan;
            String id_guru;
            String matpel; 
            String durasi_les;
            String bulan; 
            String hari;
            String harga;
            String status;
            String review = "REVIEW";
            
            String kueriSelect = "SELECT * FROM transaksi WHERE id_user = ?";
            ps = conn.prepareStatement(kueriSelect);
            ps.setInt(1, id);
            
            ResultSet rs = ps.executeQuery();
            
            DefaultTableModel tabelPesananAktif = (DefaultTableModel) kelas.tablePesananAktif.getModel();            
            
            while (rs.next()) {
                id_pesanan = String.valueOf(rs.getInt("id_transaksi"));
                id_guru = rs.getString("id_guru_les");
                matpel = rs.getString("mata_pelajaran") + " " + rs.getString("mata_pelajaran_2");
                durasi_les = String.valueOf(rs.getInt("durasi_bulan"));
                bulan = rs.getInt("bulan_mulai") + "s/d" + rs.getInt("bulan_selesai");
                hari = rs.getString("jadwal") + " " + rs.getString("jadwal_2");
                harga = String.valueOf(rs.getInt("tawar_harga"));
                status = rs.getString("status");
                
                String row[] = {id_pesanan, id_guru, matpel, durasi_les, bulan, hari, harga, status};
                tabelPesananAktif.addRow(row);
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Eksepsi akses data: " + ex.getMessage());
        }
    }//GEN-LAST:event_buttonCariActionPerformed

    private void buttonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliActionPerformed
        // TODO add your handling code here:
        new Kelas().show();
        this.dispose();
    }//GEN-LAST:event_buttonKembaliActionPerformed

    private void cbMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMulaiActionPerformed
        // TODO add your handling code here:
        int bulan_mulai = cbMulai.getSelectedIndex();
        int bulan_selesai = 0;
        int durasi = cbDurasi.getSelectedIndex();
        
        switch (durasi) {
            case 0 -> {
                bulan_selesai = bulan_mulai + 1;
            }
            case 1 -> {
                bulan_selesai = bulan_mulai + 3;
            }
            case 2 -> {
                bulan_selesai = bulan_mulai + 4;
            }
            case 3 -> {
                bulan_selesai = bulan_mulai + 6;
            }
            case 4 -> {
                bulan_selesai = bulan_mulai + 12;
            }
        }
        
        cbSelesai.setSelectedIndex(bulan_selesai % 12);
        
    }//GEN-LAST:event_cbMulaiActionPerformed

    private void cbDurasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDurasiActionPerformed
        // TODO add your handling code here:
        int bulan_mulai = cbMulai.getSelectedIndex();
        int bulan_selesai = 0;
        int durasi = cbDurasi.getSelectedIndex();
        
        switch (durasi) {
            case 0 -> {
                bulan_selesai = bulan_mulai + 1;
            }
            case 1 -> {
                bulan_selesai = bulan_mulai + 3;
            }
            case 2 -> {
                bulan_selesai = bulan_mulai + 4;
            }
            case 3 -> {
                bulan_selesai = bulan_mulai + 6;
            }
            case 4 -> {
                bulan_selesai = bulan_mulai + 12;
            }
        }
        
        cbSelesai.setSelectedIndex(bulan_selesai % 12);
    }//GEN-LAST:event_cbDurasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CariLes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CariLes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CariLes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CariLes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CariLes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCari;
    private javax.swing.JButton buttonKembali;
    private javax.swing.JComboBox<String> cbDurasi;
    private javax.swing.JComboBox<String> cbJadwal;
    private javax.swing.JComboBox<String> cbJadwal2;
    private javax.swing.JComboBox<String> cbMatpel;
    private javax.swing.JComboBox<String> cbMatpel2;
    private javax.swing.JComboBox<String> cbMulai;
    private javax.swing.JComboBox<String> cbSelesai;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelMottoApp;
    private javax.swing.JLabel labelNamaApp;
    public javax.swing.JLabel labelWelcome;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField tfHarga;
    // End of variables declaration//GEN-END:variables
}
