/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package murid;

import app_interface.Koneksi;
import com.mysql.cj.jdbc.MysqlDataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class Home extends javax.swing.JFrame implements Koneksi{
    Connection conn;
    ResultSet rs;
    PreparedStatement ps;
    MysqlDataSource dataSource;
    
    protected int id = 2;
    protected String nama = "hihi";
    Akun setting = new Akun();
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        connect();
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getNama() {
        return nama;
    }

    public void setNama(String nama) {
        this.nama = nama;
    }

    @Override
    public void connect() {
        dataSource = new MysqlDataSource();
        dataSource.setURL(Koneksi.DB_URL);
        dataSource.setUser(Koneksi.DB_USERNAME);
        dataSource.setPassword(Koneksi.DB_PASSWORD); 
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        labelNamaApp = new javax.swing.JLabel();
        labelMottoApp = new javax.swing.JLabel();
        labelWelcome = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panelAkun = new javax.swing.JPanel();
        labelAkun = new javax.swing.JLabel();
        labelLogoAkun = new javax.swing.JLabel();
        panelKelas = new javax.swing.JPanel();
        labelKelas = new javax.swing.JLabel();
        labelLogoKelas = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(45, 118, 232));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 160));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/navigation.png"))); // NOI18N

        labelNamaApp.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        labelNamaApp.setForeground(new java.awt.Color(255, 255, 255));
        labelNamaApp.setText("SIBIRU");

        labelMottoApp.setForeground(new java.awt.Color(255, 255, 255));
        labelMottoApp.setText("School Online");

        labelWelcome.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        labelWelcome.setForeground(new java.awt.Color(255, 255, 255));
        labelWelcome.setText("Halo, " + nama + "!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelMottoApp))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(labelNamaApp)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 348, Short.MAX_VALUE)
                .addComponent(labelWelcome)
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(labelWelcome))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(labelNamaApp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelMottoApp)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 300));

        panelAkun.setBackground(java.awt.SystemColor.controlHighlight);
        panelAkun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAkunMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelAkunMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelAkunMouseExited(evt);
            }
        });

        labelAkun.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelAkun.setForeground(new java.awt.Color(45, 118, 232));
        labelAkun.setText("Akun");
        labelAkun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAkunMouseClicked(evt);
            }
        });

        labelLogoAkun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/settings_48px.png"))); // NOI18N
        labelLogoAkun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLogoAkunMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelAkunLayout = new javax.swing.GroupLayout(panelAkun);
        panelAkun.setLayout(panelAkunLayout);
        panelAkunLayout.setHorizontalGroup(
            panelAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAkunLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(panelAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelLogoAkun)
                    .addGroup(panelAkunLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(labelAkun)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        panelAkunLayout.setVerticalGroup(
            panelAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAkunLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelLogoAkun)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelAkun)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panelKelas.setBackground(java.awt.SystemColor.controlHighlight);
        panelKelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelKelasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelKelasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelKelasMouseExited(evt);
            }
        });
        panelKelas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panelKelasKeyPressed(evt);
            }
        });

        labelKelas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelKelas.setForeground(new java.awt.Color(45, 118, 232));
        labelKelas.setText("Kelas");
        labelKelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelKelasMouseClicked(evt);
            }
        });

        labelLogoKelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/classroom_48px.png"))); // NOI18N
        labelLogoKelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLogoKelasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelKelasLayout = new javax.swing.GroupLayout(panelKelas);
        panelKelas.setLayout(panelKelasLayout);
        panelKelasLayout.setHorizontalGroup(
            panelKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKelasLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panelKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelLogoKelas)
                    .addGroup(panelKelasLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(labelKelas)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        panelKelasLayout.setVerticalGroup(
            panelKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKelasLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelLogoKelas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelKelas)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel5.setBackground(java.awt.SystemColor.controlHighlight);
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(45, 118, 232));
        jLabel5.setText("Cari Les");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/group_52px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(panelKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(panelAkun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelAkun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelAkunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAkunMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelAkunMouseClicked

    private void labelLogoAkunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLogoAkunMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelLogoAkunMouseClicked

    private void panelAkunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAkunMouseClicked
        // TODO add your handling code here:
        try {
            conn = dataSource.getConnection();
            
            //========================= INFORMASI MURID =========================
            String umur = null;
            String kelas = null;
            String alamat = null;
            String kontak = null;
            int jenis_kelamin = 0;
            String email = null;
            String password = null;
        
            String kueriSelect = "SELECT * FROM user WHERE id_user = ?";
            ps = conn.prepareStatement(kueriSelect);
            ps.setInt(1, id);
            rs = ps.executeQuery();
            
            while (rs.next()) {
                nama = rs.getString("nama");
                umur = rs.getString("umur");
                kelas = rs.getString("kelas");
                alamat = rs.getString("alamat");
                kontak = rs.getString("kontak");
                jenis_kelamin = rs.getInt("jenis_kelamin");
                email = rs.getString("email");
                password = rs.getString("password");
            }
            
            if (jenis_kelamin == 0) {
                setting.cbJenisKelamin.setSelectedItem("Pria");
            } else {
                setting.cbJenisKelamin.setSelectedItem("Wanita");
            }
            
            setting.tfId.setText(String.valueOf(getId()));
            setting.tfNama.setText(nama);
            setting.tfUmur.setText(umur);
            setting.tfKelas.setText(kelas);
            setting.tfKontak.setText(kontak);
            setting.taAlamat.setText(alamat);
            setting.tfEmail.setText(email);
            setting.tfPassword.setText(password);
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Eksepsi akses data: " + ex.getMessage());
        }

        setting.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panelAkunMouseClicked

    private void panelAkunMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAkunMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelAkunMouseEntered

    private void panelAkunMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAkunMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_panelAkunMouseExited

    private void labelKelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelKelasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelKelasMouseClicked

    private void labelLogoKelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLogoKelasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelLogoKelasMouseClicked

    private void panelKelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelKelasMouseClicked
        // TODO add your handling code here:
        try {
            conn = dataSource.getConnection();
            
            Kelas kelas = new Kelas();
            String id_pesanan;
            String id_guru;
            String matpel; 
            String durasi_les;
            String bulan; 
            String hari;
            String harga;
            String status;
            String review = "REVIEW";
            
            String kueriSelect = "SELECT * FROM transaksi WHERE id_user = ?";
            ps = conn.prepareStatement(kueriSelect);
            ps.setInt(1, id);
            
            ResultSet rs = ps.executeQuery();
            
            DefaultTableModel tabelPesananAktif = (DefaultTableModel) kelas.tablePesananAktif.getModel();            
            
            while (rs.next()) {
                id_pesanan = String.valueOf(rs.getInt("id_transaksi"));
                id_guru = rs.getString("id_guru_les");
                matpel = rs.getString("mata_pelajaran") + " " + rs.getString("mata_pelajaran_2");
                durasi_les = String.valueOf(rs.getInt("durasi_bulan"));
                bulan = rs.getInt("bulan_mulai") + " s/d " + rs.getInt("bulan_selesai");
                hari = rs.getString("jadwal") + " " + rs.getString("jadwal_2");
                harga = String.valueOf(rs.getInt("tawar_harga"));
                status = rs.getString("status");
                
                String row[] = {id_pesanan, id_guru, matpel, durasi_les, bulan, hari, harga, status, review};
                tabelPesananAktif.addRow(row);
                
                kelas.setVisible(true);
                this.dispose();
            }    
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Eksepsi akses data: " + ex.getMessage());
        }
    }//GEN-LAST:event_panelKelasMouseClicked

    private void panelKelasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelKelasMouseEntered
        // TODO add your handling code here

    }//GEN-LAST:event_panelKelasMouseEntered

    private void panelKelasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelKelasMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_panelKelasMouseExited

    private void panelKelasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelKelasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelKelasKeyPressed

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MousePressed

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
        CariLes cariLes = new CariLes();
        cariLes.id = id;
        cariLes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel labelAkun;
    private javax.swing.JLabel labelKelas;
    private javax.swing.JLabel labelLogoAkun;
    private javax.swing.JLabel labelLogoKelas;
    private javax.swing.JLabel labelMottoApp;
    private javax.swing.JLabel labelNamaApp;
    public javax.swing.JLabel labelWelcome;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel panelAkun;
    private javax.swing.JPanel panelKelas;
    // End of variables declaration//GEN-END:variables
}
